Add dependencies for installing OctoPrint 1.8.3
feelfreelinux/octo4a pull request #280
Opened 2022-09-20 22:13 UTC by cp2004

This is required for the newer password hashing libraries used in OctoPrint 1.8.3. We should have tested it on Octo4a as well, but as these fixes were only tested privately (due to it being a security update) it was unfortunately not done.

@feelfreelinux, if a user updates the app, how can we make sure that these dependencies are installed? Or will it be done automatically by the app? That would allow them to update to 1.8.3.

I did have a strange issue when testing this via SSH as well, which was this error:
```
ERROR: Cannot uninstall 'packaging'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
I am not completely sure what is requesting to update packaging, but it failed. Running `pip install -U packaging --ignore-installed` is a hacky way around it, but it did then allow me to complete the installation.

2022-09-22 18:39 UTC, feelfreelinux commented
Hi, thanks a lot for submitting this. Looking into the issue right now.

2022-10-03 17:21 UTC, ravikiranp123 requested changes
We need to include g++ as well. While this may not be required for installing octoprint itself, it is required for octolapse and people will certainly raise issues for that.

2022-10-07 22:41 UTC, Ltek commented
Any news on an updated Octo4a compatible with 1.8.3 & 4?

2022-10-08 16:32 UTC, cp2004 commented
Have you tried using Octo4a 1.1.2? It should be fixed.

2022-10-08 16:32 UTC, cp2004 commented
> We need to include g++ as well. While this may not be required for installing octoprint itself, it is required for octolapse and people will certainly raise issues for that.

@ravikiranp123 - that is what the 'Plugin extras' option in the app is for.

2022-10-08 16:33 UTC, closed without merging